# -*- coding: utf-8 -*-
"""Final_StockMarket.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kx7L8CMV_xwtFs0XUfeaIbigRXVgCsOO

**Surakshith Shetty - 53026240013**

**GLOBAL STOCK MARKET(FINANCIAL MARKETS) ANALYTICS**

Objectives:

Comparative Study of Global Markets – Returns, Volatility, Correlations.
Predicting Nifty 50 open direction based on global indicators.(you can decide the target market-I have considered India for which Nifty50 is the benchmark index)
Sentiment Analysis of Nifty 50 using google news data

PHASE 1: Creating Master Data

Yahoo Finance API wrapper to fetch real-time & historical stock market data
"""

import yfinance as yf

"""1. List down global market indices:
*   Nifty 50
*   Dow Jones Index
*   Nasdaq
*   Hang Seng
* Nikkei 225
* Dax
* VIX
"""

# download data of NSE,DJI,Nasdaq,IXIC,HSI,N225,GDAXI,VIX,SSE
df_nse = yf.download('^NSEI', start='2023-01-01', end='2026-01-01')
df_dji = yf.download('^DJI', start='2023-01-01', end='2026-01-01')
df_IXIC = yf.download('^IXIC', start='2023-01-01', end='2026-01-01')
df_hsi = yf.download('^HSI', start='2023-01-01', end='2026-01-01')
df_N225 = yf.download('^N225', start='2023-01-01', end='2026-01-01')
df_GDAXI = yf.download('^GDAXI', start='2023-01-01', end='2026-01-01')
df_VIX = yf.download('^VIX', start='2023-01-01', end='2026-01-01')

"""Combine global indices into a single dataframe using outer joins on date index

"""

import pandas as pd
merged_df = pd.merge(df_nse, df_dji, how='outer', left_index=True, right_index=True)
merged_df = pd.merge(merged_df, df_IXIC, how='outer', left_index=True, right_index=True)
merged_df = pd.merge(merged_df, df_hsi, how='outer', left_index=True, right_index=True)
merged_df = pd.merge(merged_df, df_N225, how='outer', left_index=True, right_index=True)
merged_df = pd.merge(merged_df, df_GDAXI, how='outer', left_index=True, right_index=True)
merged_df = pd.merge(merged_df, df_VIX, how='outer', left_index=True, right_index=True)
merged_df.columns = ['_'.join(filter(None, col)).strip() for col in merged_df.columns]
merged_df

merged_df.fillna(method='ffill', inplace=True)

"""Shift return columns by one day to generate lagged features

"""

for col in merged_df.columns:
    if col.endswith('_Return'):
        merged_df[col + '_shifted'] = merged_df[col].shift(1)
merged_df.columns

"""Remove 'Volume' columns from all dataframes"""

df_nse = df_nse.drop('Volume', axis=1, errors='ignore')
df_dji = df_dji.drop('Volume', axis=1, errors='ignore')
df_IXIC = df_IXIC.drop('Volume', axis=1, errors='ignore')
df_hsi = df_hsi.drop('Volume', axis=1, errors='ignore')
df_N225 = df_N225.drop('Volume', axis=1, errors='ignore')
df_GDAXI = df_GDAXI.drop('Volume', axis=1, errors='ignore')
df_VIX = df_VIX.drop('Volume', axis=1, errors='ignore')

"""Calculate daily returns for each index directly on merged_df"""

merged_df['NSE_Return'] = (merged_df['Close_^NSEI'].pct_change()*100).shift(1)
merged_df['DJI_Return'] = (merged_df['Close_^DJI'].pct_change()*100).shift(1)
merged_df['IXIC_Return'] = (merged_df['Close_^IXIC'].pct_change()*100).shift(1)
merged_df['HSI_Return'] = (merged_df['Close_^HSI'].pct_change()*100).shift(1)
merged_df['N225_Return'] = (merged_df['Close_^N225'].pct_change()*100).shift(1)
merged_df['GDAXI_Return'] = (merged_df['Close_^GDAXI'].pct_change()*100).shift(1)
merged_df['VIX_Return'] = (merged_df['Close_^VIX'].pct_change()*100).shift(1)

"""Compute opening price to previous day closing price ratios for selected indices"""

merged_df['NSE_Close_Ratio'] = merged_df['Open_^NSEI'] / merged_df['Close_^NSEI'].shift(1)
merged_df['N225_Close_Ratio'] = merged_df['Open_^N225'] / merged_df['Close_^N225']
merged_df['HSI_Close_Ratio'] = merged_df['Open_^HSI'] / merged_df['Close_^HSI']

import pandas as pd

# Identify daily return columns
return_columns = [col for col in merged_df.columns if 'Return' in col]

# Identify open/previous close ratio columns
ratio_columns = [col for col in merged_df.columns if 'Close_Ratio' in col]

# Combine the lists of columns, ensuring no duplicates if a column name accidentally matches both criteria
subset_columns = list(set(return_columns + ratio_columns))

# Create the subset DataFrame
returns_and_ratio_df = merged_df[subset_columns]

print("Subset DataFrame containing all daily return and open/previous close ratio columns:")
display(returns_and_ratio_df.head())

merged_df

merged_df['Quarter'] = merged_df.index.quarter
merged_df['Month'] = merged_df.index.month
merged_df['Year'] = merged_df.index.year
merged_df

"""Save the final merged and feature-engineered dataset to a CSV file for further analysis and modeling

"""

merged_df.to_csv('merged_data.csv')

"""**PHASE 2 : EDA**

1. Global Indices 5 years Performance Analytics:For each index (a to f above)

a. Box-Whisker Plot of daily returns by “YEAR”
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'Date' index is datetime type
merged_df.index = pd.to_datetime(merged_df.index)

# Extract year from the index
merged_df['Year'] = merged_df.index.year

# Identify return columns (excluding Nifty_Open_Dir and ratio columns)
return_columns = [col for col in merged_df.columns if 'Return' in col and col != 'Nifty_Open_Dir']

# Create box-whisker plots for each return column by year
for col in return_columns:
    plt.figure(figsize=(12, 6))
    sns.boxplot(x='Year', y=col, data=merged_df)
    plt.title(f'Box-Whisker Plot of Daily {col} by Year')
    plt.xlabel('Year')
    plt.ylabel('Daily Return (%)')
    plt.grid(True)
    plt.show()

"""b. Table of daily returns by “YEAR”- (n, mean and std. deviation)"""

# Ensure 'Date' index is datetime type for merged_df
merged_df.index = pd.to_datetime(merged_df.index)

# Extract year from the index and add it to merged_df
merged_df['Year'] = merged_df.index.year

# Group data by year and calculate statistics for daily returns
daily_returns_summary = merged_df.groupby('Year')[['NSE_Return', 'DJI_Return', 'IXIC_Return',
                                                    'HSI_Return', 'N225_Return', 'GDAXI_Return',
                                                    'VIX_Return']].agg(['count', 'mean', 'std'])

daily_returns_summary

"""c. Bar Plot of median daily return by “YEAR”"""

plt.figure(figsize=(12, 6))
for column in return_columns:
    median_daily_returns = merged_df.groupby('Year')[column].median()
    sns.barplot(x=median_daily_returns.index, y=median_daily_returns.values)
    plt.title(f'Median Daily Return of {column} by Year')
    plt.xlabel('Year')
    plt.ylabel('Median Daily Return')
    plt.show()

"""d. Heat Map by “YEAR” and “QUARTER” showing median/mean returns for NSEI, DJI, IXIC,HSI,N225,GDAXI,VIX"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select relevant columns for the heatmap
columns_for_heatmap = ['NSE_Return', 'DJI_Return', 'IXIC_Return',
                       'HSI_Return', 'N225_Return', 'GDAXI_Return', 'VIX_Return']

# Group data by year and quarter, calculate the median daily return
heatmap_data = merged_df.groupby(['Year', 'Quarter'])[columns_for_heatmap].median().unstack()

# Create the heatmap
plt.figure(figsize=(16, 8))
sns.heatmap(heatmap_data, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Median Daily Returns by Year and Quarter')
plt.xlabel('Index')
plt.ylabel('Year and Quarter')
plt.show()

#Group data by year and quarter, calculate the mean daily return
heatmap_data_mean = merged_df.groupby(['Year', 'Quarter'])[columns_for_heatmap].mean().unstack()

# Create the heatmap
plt.figure(figsize=(16, 8))
sns.heatmap(heatmap_data_mean, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Mean Daily Returns by Year and Quarter')
plt.xlabel('Index')
plt.ylabel('Year and Quarter')
plt.show()

"""**2.	Global Indices-Correlation Analysis**

a. Correlation Matrix of 6 years daily returns (6 by 6 matrix)
"""

# Calculate the correlation matrix of daily returns
correlation_matrix = merged_df[['NSE_Return', 'DJI_Return', 'IXIC_Return',
                               'HSI_Return', 'N225_Return', 'GDAXI_Return']].corr()

# Display the correlation matrix
print(correlation_matrix)

# Create a heatmap of the correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Daily Returns')
plt.show()

"""b. Correlation Matrix of one year 2024 daily returns (6 by 6 matrix)"""

# Filter data for the year 2024
merged_df_2024 = merged_df[merged_df['Year'] == 2024]

# Calculate the correlation matrix for 2024
correlation_matrix_2024 = merged_df_2024[['NSE_Return', 'DJI_Return', 'IXIC_Return',
                                         'HSI_Return', 'N225_Return', 'GDAXI_Return']].corr()

# Display the correlation matrix for 2024
print(correlation_matrix_2024)

# Create a heatmap of the correlation matrix for 2024
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix_2024, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Daily Returns (2024)')
plt.show()

"""**3.	Nifty 50 Daily Movement- Pre Modeling Work**

a .Define Nifty_Open_Dir=1 if Nifty 50 Open at t > Close at t-1 =0 other wise
"""

merged_df['Nifty_Open_Dir'] = merged_df.apply(lambda row: 1 if row['Open_^NSEI'] > merged_df['Close_^NSEI'].shift(1).loc[row.name] else 0, axis=1)
# Handle the first row (no previous day's close) using .loc to avoid SettingWithCopyWarning
merged_df.loc[merged_df.index[0], 'Nifty_Open_Dir'] = 0

print("Defined 'Nifty_Open_Dir' based on the condition Nifty 50 Open at t > Close at t-1:")
print(merged_df[['Open_^NSEI', 'Close_^NSEI', 'Nifty_Open_Dir']].head())

print("Value counts for Nifty_Open_Dir:")
print(merged_df['Nifty_Open_Dir'].value_counts())

print("\nSum of Nifty_Open_Dir (total days Nifty opened higher):")
print(merged_df['Nifty_Open_Dir'].sum())

"""c. Visualize/summarize global indices including VIX for 2 categories of Nifty_Open_Dir"""

# Group data by 'Nifty_Open_Dir' and calculate summary statistics for global indices
global_indices = ['NSE_Return', 'DJI_Return', 'IXIC_Return',
                  'HSI_Return', 'N225_Return', 'GDAXI_Return', 'VIX_Return']
summary_by_nifty_open_dir = merged_df.groupby('Nifty_Open_Dir')[global_indices].agg(['mean', 'median', 'std'])

# Print the summary table
print(summary_by_nifty_open_dir)

# Visualize the summary statistics using bar plots
# Correctly select columns with MultiIndex
columns_to_plot = []
for index in global_indices:
    columns_to_plot.extend([(index, 'mean'), (index, 'median')])

summary_by_nifty_open_dir[columns_to_plot].plot(kind='bar', figsize=(15, 8))
plt.title('Mean and Median of Global Indices by Nifty_Open_Dir')
plt.xlabel('Nifty_Open_Dir')
plt.ylabel('Daily Return')
plt.xticks(rotation=0)
plt.legend(title='Statistic')
plt.show()

# Box plots to visualize the distributions of global indices for different Nifty_Open_Dir values
for index in global_indices:
    plt.figure(figsize=(8, 6))
    sns.boxplot(x='Nifty_Open_Dir', y=index, data=merged_df)
    plt.title(f'Distribution of {index} by Nifty_Open_Dir')
    plt.xlabel('Nifty_Open_Dir')
    plt.ylabel(f'{index}')
    plt.show()

"""**Phase 3: Predictive Modeling**

1. Define Nifty_Dir_Open =1/0 based on direction (dependent variable)
"""

import pandas as pd

# Ensure Nifty_Open_Dir column exists in merged_df
if 'Nifty_Open_Dir' not in merged_df.columns:
    print("Creating 'Nifty_Open_Dir' as it was not found.")
    merged_df['Nifty_Open_Dir'] = merged_df.apply(lambda row: 1 if row['Open_^NSEI'] > merged_df['Close_^NSEI'].shift(1).loc[row.name] else 0, axis=1)
    merged_df.loc[merged_df.index[0], 'Nifty_Open_Dir'] = 0

# Create a new DataFrame by concatenating the desired columns
# Use .copy() to avoid SettingWithCopyWarning later if modifications are made
final_features_df = pd.concat([returns_and_ratio_df, merged_df['Nifty_Open_Dir']], axis=1)

print("Merged DataFrame 'final_features_df' containing returns, ratios, and Nifty_Open_Dir:")
display(final_features_df.head())

modeldata=final_features_df.loc[:'2025-05-31']

modeldata.shape

import statsmodels.formula.api as smf
train_df = modeldata.loc[:'2025-05-31'].copy()
train_df.info()

model = smf.logit('Nifty_Open_Dir ~ NSE_Return +  DJI_Return + IXIC_Return + GDAXI_Return + HSI_Return + N225_Return ', data = train_df).fit()

# Print the model summary
print(model.summary())

import pandas as pd
# Define the test period
test_start_date = '2025-06-01'
test_end_date = '2026-01-01'

# Create the test dataframe from final_features_df for the specified period
test_df_time = final_features_df.loc[(final_features_df.index >= test_start_date) & (final_features_df.index <= test_end_date)].copy()

# Separate features (X) and target (y) for the training set
X_train = train_df.drop('Nifty_Open_Dir', axis=1)
y_train = train_df['Nifty_Open_Dir']

# Separate features (X) and target (y) for the test set
X_test = test_df_time.drop('Nifty_Open_Dir', axis=1)
y_test = test_df_time['Nifty_Open_Dir']

# Remove any rows with NaN values in X or y for both train and test sets
# This is crucial before training models. Apply dropna on X_train/y_train and X_test/y_test separately.
train_combined = pd.concat([X_train, y_train], axis=1).dropna()
X_train = train_combined.drop('Nifty_Open_Dir', axis=1)
y_train = train_combined['Nifty_Open_Dir']

test_combined = pd.concat([X_test, y_test], axis=1).dropna()
X_test = test_combined.drop('Nifty_Open_Dir', axis=1)
y_test = test_combined['Nifty_Open_Dir']

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

"""


3. Run  Logistic Regression with Nifty Direction as dependent variable and
previous day global market returns (and VIX) as independent variables."""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

features = [
    'VIX_Return',
    'IXIC_Return',
    'NSE_Return',
    'N225_Close_Ratio',
    'GDAXI_Return',
    'NSE_Close_Ratio',
    'HSI_Return',
    'DJI_Return',
    'N225_Return',
    'HSI_Close_Ratio'
]

# Filter X_train and X_test to include only the selected features
X_train_selected = X_train[features]
X_test_selected = X_test[features]

# Fill NaN values with 0 for the selected features (already handled by dropna in previous cell, but as a safeguard)
X_train_selected = X_train_selected.fillna(0)
X_test_selected = X_test_selected.fillna(0)

# Initialize and train the logistic regression model
# Increased max_iter to help with convergence warning
model = LogisticRegression(max_iter=1000)
model.fit(X_train_selected, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_selected)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

"""6. Obtain ROC curve and AUC for train data"""

from sklearn.metrics import roc_curve, auc
# The 'const' column is not in X_train_selected for the sklearn model, so we use X_train_selected directly.
y_train_pred_proba = model.predict_proba(X_train_selected)[:, 1] # Probabilities for the positive class
fpr, tpr, thresholds = roc_curve(y_train, y_train_pred_proba)
roc_auc = auc(fpr, tpr)
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - Train Data')
plt.legend(loc="lower right")
plt.show()
print(f"AUC for train data: {roc_auc}")

"""7. Obtain threshold to balance sensitivity and specificity"""

# Find the optimal threshold that balances sensitivity and specificity
import numpy as np
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print(f"Optimal Threshold: {optimal_threshold}")

"""8. Obtain ROC curve and AUC for test data (compare with step 6)"""

# Use X_test_selected directly for prediction with the sklearn model
y_test_pred_proba = model.predict_proba(X_test_selected)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_test_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - Test Data')
plt.legend(loc="lower right")
plt.show()

print(f"AUC for test data: {roc_auc}")

"""9. Use above threshold to obtain sensitivity and specificity for test data"""

# Use the optimal threshold to classify predictions for the test set
y_pred_optimal = (y_test_pred_proba >= optimal_threshold).astype(int)
# Calculate the confusion matrix
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_optimal).ravel()
# Calculate sensitivity and specificity
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)
print(f"Sensitivity at optimal threshold: {sensitivity}")
print(f"Specificity at optimal threshold: {specificity}")

"""**Phase** 4: ML methods and compare with Binary Logistic Regression"""

import statsmodels.api as sm
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd # Ensure pandas is imported if not already

# The training and testing data prepared in previous steps are:
# X_train_selected, X_test_selected, y_train, y_test
# These are DataFrames containing the 10 features and are already cleaned (NaNs handled).

# Define the features to be used for the statsmodels Logistic Regression.
# We will use the same set of return and VIX features that appeared in the summary
# of the smf.logit model in cell LMTauozYycqV. This also avoids the 'Close_Ratio'
# features which might be highly correlated and cause singularity.
statsmodel_features = [
    'NSE_Return',
    'DJI_Return',
    'IXIC_Return',
    'HSI_Return',
    'N225_Return',
    'GDAXI_Return',
    'VIX_Return'
]

# Select these features from the already prepared X_train_selected and X_test_selected
X_train_sm_subset = X_train_selected[statsmodel_features]
X_test_sm_subset = X_test_selected[statsmodel_features]

# Add constant for statsmodels
X_train_sm = sm.add_constant(X_train_sm_subset)
X_test_sm = sm.add_constant(X_test_sm_subset)

# Fit model
# If convergence issues persist, consider increasing maxiter or trying a different optimizer (e.g., 'bfgs' or 'lbfgs')
logit_model = sm.Logit(y_train, X_train_sm).fit(maxiter=1000)

# Predictions
y_pred_prob = logit_model.predict(X_test_sm)
y_pred = [1 if p > 0.5 else 0 for p in y_pred_prob]

print(logit_model.summary())
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.linear_model import LogisticRegression
import pandas as pd # Ensure pandas is imported

# --- Re-initialize and Re-train Logistic Regression Model ---
# The 'model' variable was likely overwritten by the BERT model. Let's recreate it.

# Define the features that were used for the Logistic Regression model
features = [
    'VIX_Return',
    'IXIC_Return',
    'NSE_Return',
    'N225_Close_Ratio',
    'GDAXI_Return',
    'NSE_Close_Ratio',
    'HSI_Return',
    'DJI_Return',
    'N225_Return',
    'HSI_Close_Ratio'
]

# Assuming train_df and test_df_time are correctly loaded from previous cells
# Re-extract X_train_selected, y_train, X_test_selected, y_test for Logistic Regression

# For training data
X_train_logreg_reselected = train_df[features]
y_train_logreg_reselected = train_df['Nifty_Open_Dir'].astype(int)

# For test data
X_test_logreg_reselected = test_df_time[features]
y_test_logreg_reselected = test_df_time['Nifty_Open_Dir'].astype(int)

# Handle NaNs in the re-selected data (as was done previously for LR)
X_train_logreg_reselected = X_train_logreg_reselected.fillna(0)
X_test_logreg_reselected = X_test_logreg_reselected.fillna(0)

# Drop rows where target variable is NaN if any (important for y_train_logreg_reselected)
valid_train_indices = y_train_logreg_reselected.dropna().index
X_train_logreg_reselected = X_train_logreg_reselected.loc[valid_train_indices]
y_train_logreg_reselected = y_train_logreg_reselected.loc[valid_train_indices]

valid_test_indices = y_test_logreg_reselected.dropna().index
X_test_logreg_reselected = X_test_logreg_reselected.loc[valid_test_indices]
y_test_logreg_reselected = y_test_logreg_reselected.loc[valid_test_indices]


# Initialize and train the logistic regression model again
logreg_model = LogisticRegression(max_iter=1000)
logreg_model.fit(X_train_logreg_reselected, y_train_logreg_reselected)

# --- End Re-initialization ---

# Now use the correct 'logreg_model' to predict probabilities
y_test_pred_proba = logreg_model.predict_proba(X_test_logreg_reselected)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test_logreg_reselected, y_test_pred_proba)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - BLR Test Data')
plt.legend(loc="lower right")
plt.show()

print(f"AUC for Binary Logistic Regression test data: {roc_auc}")

"""compare with Gaussian Naive Bayes"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    confusion_matrix,
    roc_curve,
    auc,
    classification_report,
    accuracy_score
)

# ---------------------------------------------------
# 1. Train Gaussian Naive Bayes
# ---------------------------------------------------
gnb = GaussianNB()
gnb.fit(X_train_logreg_reselected, y_train_logreg_reselected)

# ---------------------------------------------------
# 2. Predict probabilities (required for ROC)
# ---------------------------------------------------
y_test_proba = gnb.predict_proba(X_test_logreg_reselected)[:, 1]

# ---------------------------------------------------
# 3. ROC Curve and AUC
# ---------------------------------------------------
fpr, tpr, thresholds = roc_curve(
    y_test_logreg_reselected, y_test_proba
)
roc_auc = auc(fpr, tpr)

# ---------------------------------------------------
# 4. Sensitivity & Specificity
# ---------------------------------------------------
sensitivity = tpr                 # True Positive Rate
specificity = 1 - fpr             # True Negative Rate

# ---------------------------------------------------
# 5. Balanced Threshold (Sensitivity ≈ Specificity)
# ---------------------------------------------------
optimal_idx = np.argmin(np.abs(sensitivity - specificity))
balanced_threshold = thresholds[optimal_idx]

print(f"\nBalanced Threshold: {balanced_threshold:.4f}")

# ---------------------------------------------------
# 6. Apply Balanced Threshold
# ---------------------------------------------------
y_pred_balanced = (y_test_proba >= balanced_threshold).astype(int)

tn, fp, fn, tp = confusion_matrix(
    y_test_logreg_reselected, y_pred_balanced
).ravel()

balanced_sensitivity = tp / (tp + fn)
balanced_specificity = tn / (tn + fp)

print(f"Sensitivity: {balanced_sensitivity:.4f}")
print(f"Specificity: {balanced_specificity:.4f}")
print(f"Difference: {abs(balanced_sensitivity - balanced_specificity):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_logreg_reselected, y_pred_balanced))

# ---------------------------------------------------
# 7. Classification Report
# ---------------------------------------------------
print("\nClassification Report:")
print(classification_report(y_test_logreg_reselected, y_pred_balanced))

# ---------------------------------------------------
# 8. ROC Curve Plot
# ---------------------------------------------------
plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, lw=2, label=f'ROC Curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], 'k--', lw=1)

# Mark the balanced threshold point
plt.scatter(
    fpr[optimal_idx],
    tpr[optimal_idx],
    color='red',
    label=f'Balanced Threshold = {balanced_threshold:.2f}'
)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve – Gaussian Naive Bayes')
plt.legend(loc='lower right')
plt.show()

print(f"\nAUC: {roc_auc:.4f}")

"""Compare with SVC"""

from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report, accuracy_score, roc_curve
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Ensure all data is numeric and handle potential NaNs
X_train_logreg_reselected = X_train_logreg_reselected.fillna(0)
X_test_logreg_reselected = X_test_logreg_reselected.fillna(0)

# Define the SVC model
svc = SVC(random_state=42, probability=True) # probability=True is needed for predict_proba

# Define the parameter grid for GridSearchCV
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'linear']
}

# Initialize GridSearchCV
grid_search = GridSearchCV(svc, param_grid, refit=True, verbose=2, cv=3, n_jobs=-1) # Use n_jobs=-1 for parallel processing

# Fit GridSearchCV to the training data
grid_search.fit(X_train_logreg_reselected, y_train_logreg_reselected)

# Get the best model from GridSearchCV
best_svc_model = grid_search.best_estimator_

# Evaluate the best model on the test data
y_pred_svc_tuned = best_svc_model.predict(X_test_logreg_reselected)

# For SVC, only use predict_proba if probability=True was set during training
# If not, use decision_function instead
if hasattr(best_svc_model, 'predict_proba'):
    y_pred_proba_svc_tuned = best_svc_model.predict_proba(X_test_logreg_reselected)[:, 1]
else:
    # Use decision_function as alternative for ROC AUC
    y_pred_proba_svc_tuned = best_svc_model.decision_function(X_test_logreg_reselected)

# Calculate metrics
accuracy_tuned = accuracy_score(y_test_logreg_reselected, y_pred_svc_tuned)
conf_matrix_tuned = confusion_matrix(y_test_logreg_reselected, y_pred_svc_tuned)
class_report_tuned = classification_report(y_test_logreg_reselected, y_pred_svc_tuned)
roc_auc_tuned = roc_auc_score(y_test_logreg_reselected, y_pred_proba_svc_tuned)

# Extract sensitivity (recall for positive class) and specificity from confusion matrix
tn, fp, fn, tp = conf_matrix_tuned.ravel()
sensitivity_tuned = tp / (tp + fn)
specificity_tuned = tn / (tn + fp)

print(f"\n--- Evaluation of Tuned SVC Model on Test Data ---")
print(f"Accuracy: {accuracy_tuned:.4f}")
print(f"ROC AUC: {roc_auc_tuned:.4f}")
print(f"Sensitivity: {sensitivity_tuned:.4f}")
print(f"Specificity: {specificity_tuned:.4f}")
print(f"\nConfusion Matrix:\n{conf_matrix_tuned}")
print(f"\nClassification Report:\n{class_report_tuned}")

# Plot ROC curve for the tuned model
fpr_tuned, tpr_tuned, _ = roc_curve(y_test_logreg_reselected, y_pred_proba_svc_tuned)

plt.figure(figsize=(8, 6))
plt.plot(fpr_tuned, tpr_tuned, color='darkorange', lw=2,
         label=f'ROC curve (AUC = {roc_auc_tuned:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve - Tuned SVC Test Data')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print(f"\nTuned SVC Model achieved ROC AUC of {roc_auc_tuned:.4f}, Sensitivity of {sensitivity_tuned:.4f}, and Specificity of {specificity_tuned:.4f}.")

"""Compare with LSTM

Step 1: Prepare Data (Scaling + Sequences)
"""

import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Choose target index (example: NIFTY)
# Define market_df explicitly from merged_df
market_df = merged_df.copy()
target_col = "Open_^NSEI"
data = market_df[[target_col]].dropna()

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

def create_sequences(data, seq_len=60):
    X, y = [], []
    for i in range(seq_len, len(data)):
        X.append(data[i-seq_len:i, 0])
        y.append(data[i, 0])
    return np.array(X), np.array(y)

SEQ_LEN = 60
X, y = create_sequences(scaled_data, SEQ_LEN)

# Train-test split
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# Reshape for LSTM
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], 1))

"""Step 2: Build LSTM Model"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(SEQ_LEN, 1)),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(1)
])

model.compile(optimizer="adam", loss="mse")
model.summary()

"""Step 3: Train LSTM"""

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=32
)

"""Step 4: Predict & Inverse Scale"""

predictions = model.predict(X_test)
predictions = scaler.inverse_transform(predictions.reshape(-1, 1))
actual = scaler.inverse_transform(y_test.reshape(-1, 1))

"""Step 5: Plot Prediction"""

plt.figure(figsize=(12,6))
plt.plot(actual, label="Actual")
plt.plot(predictions, label="Predicted")
plt.title("LSTM Stock Price Prediction")
plt.legend()
plt.show()

"""Compare with KNN"""

#Step 1: Feature Scaling (MANDATORY for KNN)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_logreg_reselected)
X_test_scaled  = scaler.transform(X_test_logreg_reselected)

#Step 2: Train Model
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(
    n_neighbors=7,     # try 5–15
    metric='minkowski' # default (Euclidean)
)

knn_model.fit(X_train_scaled, y_train_logreg_reselected)

#Step 3: Evaluation + ROC–AUC
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    auc
)
import matplotlib.pyplot as plt

# Predictions
y_pred_knn = knn_model.predict(X_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test_logreg_reselected, y_pred_knn))
print("\nConfusion Matrix (KNN):\n", confusion_matrix(y_test_logreg_reselected, y_pred_knn))
print("\nClassification Report (KNN):\n", classification_report(y_test_logreg_reselected, y_pred_knn))

# ROC & AUC
y_test_pred_proba_knn = knn_model.predict_proba(X_test_scaled)[:, 1]

fpr_knn, tpr_knn, _ = roc_curve(y_test_logreg_reselected, y_test_pred_proba_knn)
roc_auc_knn = auc(fpr_knn, tpr_knn)

plt.figure(figsize=(7, 5))
plt.plot(fpr_knn, tpr_knn, lw=2, label=f'ROC curve (AUC = {roc_auc_knn:.2f})')
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve – KNN (Time-Based Split)')
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

print(f"AUC for KNN test data: {roc_auc_knn:.4f}")

"""**PHASE 5 - Sentiment Analysis**"""

!pip install pygooglenews

import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter
from pygooglenews import GoogleNews
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Added to download the missing resource

# ---------------------------
# STEP 1 — LOAD GOOGLE NEWS
# ---------------------------
gn = GoogleNews()

s = gn.search('NSE', from_='2025-12-01', to_='2026-03-01')
p = gn.search('nifty', from_='2025-12-01', to_='2026-03-01')
Q = gn.search('NIFTY', from_='2025-12-01', to_='2026-03-01')

def extract_news(result_dict):
    return [
        {'Title': entry['title'], 'Published Date': entry['published']}
        for entry in result_dict['entries']
    ]

df  = pd.DataFrame(extract_news(s))
df1 = pd.DataFrame(extract_news(p))
df2 = pd.DataFrame(extract_news(Q))

concat = pd.concat([df, df1, df2], ignore_index=True)
concat['Published Date'] = pd.to_datetime(concat['Published Date'])
concat = concat.drop_duplicates(subset='Title').sort_values('Published Date')

# --------------------------------
# STEP 2 — TOKENIZATION + TOP WORDS
# --------------------------------
stop_words = set(stopwords.words('english'))
additional = {"nifty", "nse", "india","SBEI","market", "stock", "stocks", "sensex","livemint","indian","times","today","key","moneycontrol","ipo",
              "com","bse","trade","trading","exchange","reuters","economic","finance","yahoo","Earning","ddnews","global","Price","holiday","share","earning","points","mints","Highlights","Limited"
              ,"NDTV","CNBC","December","markets","earnings","Analysts","Financial","capital",""}
stop_words.update(additional)

def tokenize_text(text):
    tokens = word_tokenize(text.lower())
    tokens = [t for t in tokens if t.isalpha() and t not in stop_words]
    return tokens

concat["Tokens"] = concat["Title"].apply(tokenize_text)

# Top frequent words across all news
all_tokens = [tok for row in concat["Tokens"] for tok in row]
word_freq = Counter(all_tokens).most_common(20)

print("\n● Top 20 Words:")
for w, f in word_freq:
    print(f"{w}: {f}")

# ------------------------------
# STEP 3 — FINBERT SENTIMENT
# ------------------------------
model_name = "ProsusAI/finbert"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

labels = ["negative", "neutral", "positive"]

def finbert_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    scores = torch.nn.functional.softmax(outputs.logits, dim=1)
    sentiment = labels[scores.argmax()]
    confidence = float(scores.max())
    return sentiment, confidence

concat["Sentiment"], concat["Confidence"] = zip(*concat["Title"].apply(finbert_sentiment))

# ------------------------------
# STEP 4 — SAVE FINAL OUTPUT
# ------------------------------
concat.to_csv("news_with_sentiment.csv", index=False)

print("\n✅ Finished! File saved: news_with_sentiment.csv\n")

!pip install wordcloud

import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Load the news data with sentiment
news_df = pd.read_csv('news_with_sentiment.csv')

# Combine all the titles into a single string
all_titles = ' '.join(news_df['Title'].dropna().tolist())


# Generate a word cloud image, excluding the specified stopwords
wordcloud = WordCloud(width=800, height=400, background_color='white', stopwords=stop_words).generate(all_titles)

# Display the generated image:
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of News Titles (with stopwords removed)')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the news data with sentiment
news_df = pd.read_csv('news_with_sentiment.csv')

# Count the occurrences of each sentiment
sentiment_counts = news_df['Sentiment'].value_counts().reindex(['positive', 'neutral', 'negative'])

# Create a bar plot
plt.figure(figsize=(8, 6))
sns.barplot(x=sentiment_counts.index, y=sentiment_counts.values, palette='viridis')
plt.title('Sentiment Distribution of News Titles')
plt.xlabel('Sentiment')
plt.ylabel('Number of Articles')
plt.show()